name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Run tree
      run: tree

    - name: Make ex00
      run: make
      working-directory: ex00

    - name: Re-make ex00
      run: make re
      working-directory: ex00

    - name: View contents of ex00
      run: nm -C zombie
      working-directory: ex00
    
    - name: Run ex00
      run: ./zombie
      working-directory: ex00
    
