name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Run tree
      run: tree

    - name: Make ex00
      run: make
      working-directory: ex00

    - name: Re-make ex00
      run: make re
      working-directory: ex00

    - name: View contents of ex00
      run: nm -C zombie
      working-directory: ex00
    
    - name: Run ex00
      run: ./zombie
      working-directory: ex00
    
    - name: Make ex01
      run: make
      working-directory: ex01

    - name: Re-make ex01
      run: make re
      working-directory: ex01

    - name: View contents of ex01
      run: nm -C zombie
      working-directory: ex01
    
    - name: Run ex01
      run: ./zombie
      working-directory: ex01

    - name: Make ex02
      run: make
      working-directory: ex02

    - name: Re-make ex02
      run: make re
      working-directory: ex02

    - name: View contents of ex02
      run: nm -C brain
      working-directory: ex02
    
    - name: Run ex02
      run: ./brain
      working-directory: ex02

    - name: Make ex03
      run: make
      working-directory: ex03

    - name: Re-make ex03
      run: make re
      working-directory: ex03

    - name: View contents of ex03
      run: nm -C weapon
      working-directory: ex03
    
    - name: Run ex03
      run: ./weapon
      working-directory: ex03

    - name: Make ex04
      run: make
      working-directory: ex04

    - name: Re-make ex04
      run: make re
      working-directory: ex04

    - name: View contents of ex04
      run: nm -C sed
      working-directory: ex04
    
    - name: Run ex04 tests
      run: bash tests.sh
      working-directory: ex04

    - name: Make ex05
      run: make
      working-directory: ex05

    - name: Re-make ex05
      run: make re
      working-directory: ex05

    - name: View contents of ex05
      run: nm -C harl
      working-directory: ex05
    
    - name: Run ex05
      run: ./harl
      working-directory: ex05
    
    - name: Make ex06
      run: make
      working-directory: ex06

    - name: Re-make ex06
      run: make re
      working-directory: ex06

    - name: View contents of ex06
      run: nm -C harlFilter
      working-directory: ex06
    
    - name: Run ex06 | DEBUG
      run: ./harlFilter DEBUG
      working-directory: ex06
    
    - name: Run ex06 | INFO
      run: ./harlFilter INFO
      working-directory: ex06
    
    - name: Run ex06 | WARNING
      run: ./harlFilter WARNING
      working-directory: ex06
    
    - name: Run ex06 | ERROR
      run: ./harlFilter ERROR
      working-directory: ex06
    
    - name: Run ex06 | Non Level
      run: ./harlFilter "I hate mondays"
      working-directory: ex06
