name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Run tree
      run: tree

    - name: Make ex00
      run: make
      working-directory: ex00

    - name: Re-make ex00
      run: make re
      working-directory: ex00

    - name: View contents of ex00
      run: nm -C zombie
      working-directory: ex00
    
    - name: Run ex00
      run: ./zombie
      working-directory: ex00
    
    - name: Make ex01
      run: make
      working-directory: ex01

    - name: Re-make ex01
      run: make re
      working-directory: ex01

    - name: View contents of ex01
      run: nm -C zombie
      working-directory: ex01
    
    - name: Run ex01
      run: ./zombie
      working-directory: ex01

    - name: Make ex02
      run: make
      working-directory: ex02

    - name: Re-make ex02
      run: make re
      working-directory: ex02

    - name: View contents of ex02
      run: nm -C brain
      working-directory: ex02
    
    - name: Run ex02
      run: ./brain
      working-directory: ex02

    - name: Make ex03
      run: make
      working-directory: ex03

    - name: Re-make ex03
      run: make re
      working-directory: ex03

    - name: View contents of ex03
      run: nm -C weapon
      working-directory: ex03
    
    - name: Run ex03
      run: ./weapon
      working-directory: ex03

    - name: Make ex04
      run: make
      working-directory: ex04

    - name: Re-make ex04
      run: make re
      working-directory: ex04

    - name: View contents of ex04
      run: nm -C sed
      working-directory: ex04
    
    - name: Output sample input
      run: cat input.txt
      working-directory: ex04
    
    - name: Replace Linux with Windows | Own
      run: ./sed input.txt Linux Windows
      working-directory: ex04
    
    - name: Replace Linux with Windows | sed
      run: < input.txt sed 's/Linux/Windows/g' > sed.output.txt
      working-directory: ex04

    - name: diff outputs
      run: diff -s sed.output.txt input.txt.replace
      working-directory: ex04

    - name: Replace the with 7H3 | Own
      run: ./sed input.txt the 7H3
      working-directory: ex04
    
    - name: Replace the with 7H3 | sed
      run: < input.txt sed 's/the/7H3/g' > sed.output.txt
      working-directory: ex04

    - name: diff outputs
      run: diff -s sed.output.txt input.txt.replace
      working-directory: ex04
    
    - name: Replace spaces with underscores | Own
      run: ./sed input.txt " " _
      working-directory: ex04
    
    - name: Replace spaces with underscores | sed
      run: < input.txt sed 's/ /_/g' > sed.output.txt
      working-directory: ex04

    - name: diff outputs
      run: diff -s sed.output.txt input.txt.replace
      working-directory: ex04

    - name: 1337 Replace | Own
      run: ./sed loremipsum.txt a 4 && ./sed loremipsum.txt.replace e 3 && ./sed loremipsum.txt.replace.replace t 7 && ./sed loremipsum.txt.replace.replace.replace l 1 && ./sed loremipsum.txt.replace.replace.replace.replace o 0 && ./sed loremipsum.txt.replace.replace.replace.replace.replace s 5
      working-directory: ex04
    
    - name: 1337 Replace | sed
      run: < loremipsum.txt sed 's/a/4/g' | sed 's/e/3/g' | sed 's/t/7/g' | sed 's/l/1/g' | sed 's/o/0/g' | sed 's/s/5/g' > sed.output.txt
      working-directory: ex04

    - name: diff outputs
      run: diff -s sed.output.txt loremipsum.txt.replace.replace.replace.replace.replace
      working-directory: ex04
